packages:
  - packages/*
  - demo/*

overrides:
  vite: ^8

allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  protobufjs: false
  sharp: true
  unrs-resolver: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@entwico/*'
